### ISSUE TITLE
Repository Transferred to new Organization. Is it Working Correctly? New Members?

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#21]
As requested by @yeeunmariakim, I have transfered the `gkapfham/gatorgrouper` repository to the GatorGrouper organization. Can a project manager confirm that this is working correctly? Additionally, we will now need to ensure that all of the members of the previous repository can access the source code for this repository. That is, we need to make sure that everyone can create branches and push to them without resorting to have to fork the repository. However, we also need to ensure that only the designated project administrators can push to master and approve the pull requests.

**Comment by eltmanm** [comment]
Cannot access any information other than the list of users on the new repository

**Comment by yeeunmariakim** [comment]
@eltmanm the repository isn't changing--we are continuing development on this repository. Just the ownership of the repository has changed. The transfer included all of the GitHub issues, pull requests, and branches. Really, no one should see any major impacts other than non-project managers not being able to merge pull requests into master.

**Comment by yeeunmariakim** [comment]
@gkapfham I have made all the project managers who have accepted the invitation to join the organization "Owners" of the GatorGrouper organization. @bonnettd and @dillam will be made owners as well when they join the organization. I have also configured the Settings of the gatorgrouper repository so that the `master` branch is protected. This means that pull requests reviews are required before merging, the pull request must be reviewed by a Code Owner (i.e. project managers), and only project managers are able to push to the `master` branch.

**Comment by eltmanm** [comment]
cannot see or access code, or clone repository from the new one

**Comment by yeeunmariakim** [comment]
@eltmanm what URL are you using to reply to this issue?

**Comment by yeeunmariakim** [comment]
@eltmanm you are a member of the GatorGrouper organization and have member-level access, from what I can see.

**Comment by eltmanm** [comment]
shit nevermind I get it now.
'Organization' wasn't clicking til just now

**Comment by eltmanm** [comment]
sorry

**Comment by delgrecoj** [comment]
Everything is working as expected.
