### ISSUE TITLE
Standard for Commit Messages?

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#22]
Currently, this project does not have a standard for commit messages. So, some commits start with a capital letter and others do not. I suggest that we following the [standard set by Tim Pope](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). That is, I judge that the messages should start with a capital letter and be short and to the point. If needed, there can be summary comments below the one-line commit message. Agreed?

**Comment by delgrecoj** [comment]
Have known about his standard for several years but never use it... have always find that in practice the leading capitals get confusing, that 50 characters is too restrictive, and that it just looks weird.

I'm for allowing flexibility with the messages, just as long as they're *descriptive* and to the point.

![2017-10-04-180219_544x687_scrot](https://user-images.githubusercontent.com/21695244/31202156-882941b4-a92f-11e7-8723-7001b01b9c2d.png)

**Comment by yeeunmariakim** [comment]
@delgrecoj I appreciate your screenshot of the results of OBC’s “update” script. Personally, I think always committing with the same commit message is very efficient, and relieves some mental load associated with development. 😛

Jokes aside, I agree with @delgrecoj that we should not require students to comply to the Tim Pope standard. After learning about it in class, I tried to follow it in my own commit messages for a while and found that I spent more time thinking about the format of my message than the content—this, to me, was time wasted since the format of a commit message did not improve the value of the message nearly as much as making sure the content was thoroughly descriptive. Also, I feel that following the Tim Pope format did little to improve the readability of a git log, granted that I wrote free of typos and with proper grammar.

This is definitely just my opinion, and I’d love to hear everyone else’s two cents. I have observed in industry and in open source projects that teams generally do not require contributors to abide by many strict standards—I think this would bog down and discourage collaborators.

**Comment by sutterj** [comment]
I think that as long as the message gives at least a slight idea of the content of the commit then it would not necessarily need to adhere to any sort of standard.

**Comment by yeeunmariakim** [comment]
@sutterj I would say "good" instead of "slight"--commit message should be descriptive enough to understand what content has been added.

**Comment by delgrecoj** [comment]
(closed by consensus of the project managers at the meeting this evening)
