### ISSUE TITLE
Comprehensive Diagnostic Output When Run in Verbose Mode

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#4]
Currently, the system only provides limited verbose mode output. However, there are several aspects of the system &mdash; especially those that result from the resolution of other issues &mdash; that would benefit from further debugging output. Finally, it would be useful if there was a way to control the level of debugging output beyond having a single flag that stipulates whether debugging output does or does not display. Perhaps it might be worthwhile to investigate the use of a logging framework for the Python 3 programming language?

**Comment by shafferz** [comment]
Going to investigate: "...the use of a logging framework for the Python 3 programming language," and also going to brush up on Python in general.

**Comment by castellanosr** [comment]
I am also looking into the use of a logging framework for the Python 3 programming language as well as various debugging methods so that we will be better able to chose a tactic/path to follow.

**Comment by castellanosr** [comment]
This is ambiguous because we do not know how much output is desired, how many levels of output is desired, and how the output should be produced (file vs terminal window).

**Comment by castellanosr** [comment]
Check with developers to see how extensive they want logging to be.

**Comment by castellanosr** [comment]
Requirements are not complete. Who/where should putting the teams in an actual file occur?

**Comment by castellanosr** [comment]
The customer mentioned that this is a less relevant" task. Meaning, there is not a specific level of outputs desired.

**Comment by shafferz** [comment]
@mendezjw, @delgrecoj, and @dillam: Can you guys check with your teams while you're working on issues #12, #13, and #14 to let us know what kinds of errors/bugs you'd be expecting to come up in a diagnostic output/debugger from the code that you are currently implementing. If I tagged the wrong team leaders for the aforementioned issues, please let me know!

**Comment by yeeunmariakim** [comment]
@shafferz I have created a new pull request that would incorporate the change to a logging framework. In the implementation, the logging level is determined by a command-line argument. If "-d" or "--debug" is passed in, then the logging framework will display all of the strings passed into `logging.debug()` and logging methods of higher priority (which are all the rest since `logging.debug()` is of lowest priority). If "-v" or "--verbose" is passed in, then the strings passed into the `logging.info()` method and methods above in priority (all but `logging.debug()`) will be displayed. If no flags related to diagnostic output are passed in, then all strings passed into the `logging.error()` method and methods above in priority (i.e. `logging.critical()) will be displayed.

**Comment by shafferz** [comment]
@yeeunmariakim The initial implementation looks good to me, as do the changes we made in person during our meetup today. Let me know if the other team leaders need us to implement the logging structure in their functions as well, which is something that I would happily do.

**Comment by yeeunmariakim** [comment]
The set up for the logging has been merged into master in pull request #35 . Keeping this issue open because we will need to verify that others are logging in their implementations following the instructions provided in the repository Wiki.

**Comment by yeeunmariakim** [comment]
Closing because we have verified that new code has included logging statements.
